# Generated by Django 5.0.4 on 2024-05-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('nombreProyecto', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombreEstudiante', models.CharField(max_length=50)),
                ('nombrePatrocinador', models.CharField(max_length=50)),
                ('nombreTema', models.CharField(max_length=30)),
            ],
        ),
    ]
